// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp_70ZDNmQFvfJIw5NOkk5vt3mHUTaYUM',
    appId: '1:21779974087:web:3ebd8355bc1211984afbe2',
    messagingSenderId: '21779974087',
    projectId: 'pesanruang-402b1',
    authDomain: 'pesanruang-402b1.firebaseapp.com',
    storageBucket: 'pesanruang-402b1.appspot.com',
    measurementId: 'G-63D3SBGEJF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH4A2YABIUWbz_JPAzTjEYe4-MiS1x2A4',
    appId: '1:21779974087:android:002f2ba759bcdba34afbe2',
    messagingSenderId: '21779974087',
    projectId: 'pesanruang-402b1',
    storageBucket: 'pesanruang-402b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0RxET99CLDHIbW2i5mGnotBePCDEyKLg',
    appId: '1:21779974087:ios:50c6db4c7d851b114afbe2',
    messagingSenderId: '21779974087',
    projectId: 'pesanruang-402b1',
    storageBucket: 'pesanruang-402b1.appspot.com',
    iosBundleId: 'com.example.pemesananRuangStudi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0RxET99CLDHIbW2i5mGnotBePCDEyKLg',
    appId: '1:21779974087:ios:50c6db4c7d851b114afbe2',
    messagingSenderId: '21779974087',
    projectId: 'pesanruang-402b1',
    storageBucket: 'pesanruang-402b1.appspot.com',
    iosBundleId: 'com.example.pemesananRuangStudi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCp_70ZDNmQFvfJIw5NOkk5vt3mHUTaYUM',
    appId: '1:21779974087:web:ccea19270f8393684afbe2',
    messagingSenderId: '21779974087',
    projectId: 'pesanruang-402b1',
    authDomain: 'pesanruang-402b1.firebaseapp.com',
    storageBucket: 'pesanruang-402b1.appspot.com',
    measurementId: 'G-LHW0NSECG3',
  );
}
